### ISSUE TITLE
Get Wh for shorter period

### ISSUE THREAD

**Issue by iBobik** [Heckie75/voltcraft-sem-6000#1]
If I understand README correctly no measurement command measures power consumption (Wh) but just current (W or A). Just recorded data can show power consumption but by hours and days.

Is it possible to get power consumption for shorter periods like 5s or minute?

**Comment by Heckie75** [comment]
The sem-6000 records data by itself without connection to your PC with three different scopes
1. aggregated per hour (call `--data day`)
2. aggregated per day (call `--data month`)
3. aggregated per month (call `--data year`)

There is no more detailled measurement implemented in SEM 6000. 

You can continously take measurements by using the `--measure` command. By doing it this way the device is connected to your PC the whole time
```
$ sem-6000 FC:69:47:06:CB:C6 0000 --measure header --measure
Timestamp       Power   Volt (V)        Ampere (A)      Watt (W)        Frequency (Hz)  Power factor
2019-10-26 06:27:17     0       233     0.0     0.0     50      n/a
2019-10-26 06:27:17     0       233     0.0     0.0     50      n/a
2019-10-26 06:27:18     0       233     0.0     0.0     50      n/a
2019-10-26 06:27:19     0       233     0.0     0.0     50      n/a
2019-10-26 06:27:20     0       233     0.0     0.0     50      n/a
2019-10-26 06:27:20     0       233     0.0     0.0     50      n/a
2019-10-26 06:27:21     0       233     0.0     0.0     50      n/a
```

The Volcraft SEM 3600 is able to record data by itself without permanent connection on minute-level.

**Comment by iBobik** [comment]
--measure would be nice but it shows just Watts - snapshot from one specific time, but not Watt hours - cumulative consumption from last request to now.

Jan Pobořil
https://honza.poboril.cz/

**Comment by Heckie75** [comment]
The smart meter returns also interim results, e.g. a value of the current running hour.
You could query this interim result by this command

sem-6000 Lamp --data day --print | tail -n1 | cut -f2

If you do this every 10-15 minutes you could calculate the Wh by youself. However, i know that this is not very precise. It is just a workaround since the SEM6000 is not able to raise data in shorter periods.

For more detailled measurements I recommend to look for a SEM3600BT.
