### ISSUE TITLE
connect error: Function not implemented (38)

### ISSUE THREAD

**Issue by jfdzar** [Heckie75/voltcraft-sem-6000#13]
Since this week I am getting this error when executing the script.
Is something similar happening to anyone?

connect error: Function not implemented (38)
    while executing
"exec gatttool -b $sem(mac) --characteristics > $hndfile"
    (procedure "setup_characteristics" line 6)
    invoked from within
"setup_characteristics"
    (procedure "init_handles" line 11)
    invoked from within
"init_handles"
    (procedure "init" line 9)
    invoked from within
"init $INIT(auth)"
    ("^sync$" arm line 3)
    invoked from within
"switch -regexp $command {

    ^sync$ {

      init $INIT(auth)
      req_sync

    }
    ^status$ {

      init $INIT(auth)
      capture_measurement..."
    (procedure "do_command" line 12)
    invoked from within
"do_command $param"
    ("while" body line 13)
    invoked from within
"while { 1 } {

  set param [ lindex $argv 0 ]
  set argv [ lrange $argv 1 end ]

  if { [string range $param 0 1 ] == "--" } {
    set param [string r..."
    (file "./sem-6000.exp" line 3580)

**Comment by bartekmotyl** [comment]
I get exactly the same error. The script was working fine (`Version: 2021-10-16`), but stopped working after upgrade to `Version: 2022-01-12`

**Comment by s-light** [comment]
for me this error shows up when the device is far away... (~5m)

the scan shows the device - 
but a connect fails..
if i move my laptop very near (<= 1m) it works again..

**Comment by s-light** [comment]
just stumbled across the same thing again ;-)
@Heckie75  would it be easy to catch this condition and give a user friendly message?

**Comment by Heckie75** [comment]
@s-light 
Maybe it would be possible to catch an error but it won't get more precise. This  error and message are thrown by ```gatttool``` which is the underlying tool provided by the bluez bluetooth stack. Actually ```gatttool``` should throw more precise errors but ```gatttool``` is deprecated as far as I know.  

If I had more time I would rewrite the tool by utilizing Python and libs since controlling ```gatttool``` by using ```expect``` always was a workaround. However, unfortunately I haven't the time and in general it works ;-)

I have started writing Linux tools for Bluetooth devices (see my repo) years ago when there weren't many alternatives. Nowadays I think about switching to _Tasmota_ devices. Unfortunately I have learned that the connection problems are the same with any devices (thermostat, bulbs, switches) driven by bluetooth LE.

**Comment by s-light** [comment]
@Heckie75 yeah - faire enough ;-) .....
Thanks for writing it in the first place!!!

do the thinks you enjoy to do ....
and i know from myself - if things *work* i have no motivation to redo them....
and your tool was the one that basically worked out of the box! :+1: 
(i tried another one and did not get it to work...)

Bluetooth and connection is a :crystal_ball:  thing.....
my computer sometimes decides that he does not know he has a Bluetooth adapter...
and after some restarted it may be back working just fine...
its the same story with devices and connections i think ;-)

**Comment by MxPie200** [comment]
@Heckie75 
Any updates on this topic?
I have the same problem and it is not related to long-range as s-light stated.
Are there any workarounds to get this thing working again?

**Comment by Heckie75** [comment]
@s-light I can't reproduce this problem. I use my sem-6000 everyday and I don't have this issue. I think that it is related to bluez. Which bluez version do you use?

Maybe you can try the python implementation which is provided here https://github.com/moormaster/python3-voltcraft-sem6000

**Comment by s-light** [comment]
as i only borrowed the device i cant test any longer..

**Comment by MxPie200** [comment]
@Heckie75
Yes I've already seen this implementation - but sadly, it doesn't work anyway.

Im getting connection error again:
`python3 sem6000-cli-demo.py  B3:00:00:00:64:7A pin 0000 get_hardware_version
connecting to B3:00:00:00:64:7A ...
command failed (0 retries) - repeating after 0.1 seconds...
connecting to B3:00:00:00:64:7A ...
Traceback (most recent call last):
  File "/home/max/Desktop/python3-voltcraft-sem6000/sem6000-cli-demo.py", line 111, in <module>
    sem6000 = sem6000.SEM6000(deviceAddr, debug=True)
  File "/home/max/Desktop/python3-voltcraft-sem6000/sem6000/sem6000.py", line 111, in __init__
    self.connect(deviceAddr)
  File "/home/max/Desktop/python3-voltcraft-sem6000/sem6000/repeat_on_failure_decorator.py", line 34, in decorated_function
    reconnect()
  File "/home/max/Desktop/python3-voltcraft-sem6000/sem6000/repeat_on_failure_decorator.py", line 12, in reconnect
    reconnectable._reconnect()
  File "/home/max/Desktop/python3-voltcraft-sem6000/sem6000/sem6000.py", line 137, in _reconnect
    raise e
  File "/home/max/Desktop/python3-voltcraft-sem6000/sem6000/sem6000.py", line 131, in _reconnect
    self._bluetooth_lowenergy_interface.connect(self.connection_settings["device_address"])
  File "/home/max/Desktop/python3-voltcraft-sem6000/sem6000/bluetooth_lowenergy_interface/bluepy_interface.py", line 116, in connect
    raise e
  File "/home/max/Desktop/python3-voltcraft-sem6000/sem6000/bluetooth_lowenergy_interface/bluepy_interface.py", line 113, in connect
    self._peripheral.connect(mac_address, btle.ADDR_TYPE_PUBLIC, iface)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral B3:00:00:00:64:7A, addr type: public
`
I have Bluez Version 5.55

**Comment by MxPie200** [comment]
Or what also comes in my mind, is it possible that the sem6000 device has a problem - because the MAC Adress is B3:00:00:00:64:7A. Don't know if it is normal but some kind of unusual that a MAC adress has "00" at three parts of the adress?
(But in sem6000 android-app, i can normal connect to it..)

**Comment by Heckie75** [comment]
@MxPie200 
It is not realistic that the problem is related to the MAC address. So far we have found out that connection does neither work with my script nor with the script based on python. In addition error messages show that error occur on low level, at least not on something like application level.

You could try out the following.
1. Does the device connect with the official Android or iOS app?
2. Can you control the device via the app as expected? Turn on / off, Does it display the measurements in real time?
3. The app displays the current firmware version if you keep pressing the device entry and open settings that appear on at the bottom. I have installed the app and it displays 1.13a for the first device and 1.17a for the other that I own. BTW: It offers me to upgrade to 1.24. I think twice if I do this ;-)
4. Have you made sure that the device is not connected to other devices, e.g. your smartphone if you try to connect via script?

----
![signal-2024-04-20-091758](https://github.com/Heckie75/voltcraft-sem-6000/assets/10388395/764314ad-b394-418f-956d-6fdc7f5b9063)
![signal-2024-04-20-091814](https://github.com/Heckie75/voltcraft-sem-6000/assets/10388395/4425152e-2083-43b6-9ac6-1e5d5ee2ff38)
![signal-2024-04-20-091832](https://github.com/Heckie75/voltcraft-sem-6000/assets/10388395/1462079e-2a8a-49ed-8bf0-4c29f265f9e0)


----

Edit:
I have made the firmware update on both devices. I can confirm that the script  work with latest firmware 1.24:
```
$ sem-6000 Laptop --device --print
Device:
  Mac:                  B0:B1:13:61:B1:D1
  Device PIN:           xxxx
  Name:                 Voltcraft
  Vendor:               VOLCFT
  Serial:               ML01D1012000000
  Firmware:             1.24
  Hardware:             2.0
  MTU:                  23
  Alias:                Laptop
```

**Comment by MxPie200** [comment]
@Heckie75 
Thanks for your effort, in the meantime i figured out the problem.
I am using an Raspberry Pi 4B with internal WLAN/Bluetooth.
It seems like they're not working properly at the same time, i inserted an USB Bluetooth Dongle and retried.
And it works again - so it was a hardware-related problem of Raspberry Pi's internals !
