### ISSUE TITLE
Sending PIN is not needed for capturing measurement

### ISSUE THREAD

**Issue by cmur2** [Heckie75/voltcraft-sem-6000#5]
By accident I found out that after opening the BLE connection to the Voltcraft you can directly transmit a [Capture Measurement](https://github.com/Heckie75/voltcraft-sem-6000/blob/master/API.md#capture-measurement) command and you will recieve a valid BLE notification containing actual values.

I tried and for other requests like setting the power switch/LED ring on/off you will receive a "Authorization invalid/missing PIN" BLE notification but for capture measurement it is just `Capture measurement response 0x0400` BLE notification.

Edit: is there an easy way to account for this in the script?

**Comment by Heckie75** [comment]
Interesting. There are also ways / other commands to get the current measement w/o pin. But I think that the normal use case is to send it since you know it.

In order to keep the interface (CLI) for all commands simular, I actually don't want to change anythink. But of course you are free to fork this source code and change it to your needs. 

Best regards and happy easter
